### ISSUE TITLE
Optimise imports

### ISSUE THREAD

**Issue by aplowman** [hpcflow/matflow-new#229]
Some imports can be placed inside a function scope to ensure they do run when not needed. This will improve start-up time.

In `matplotlib.param_classes.seeds`, we import `matplotlib`, but it is only need in the `MicrostructureSeeds.show` method.

**Comment by dkfellows** [comment]
This task appears to be done; all imports now appear to either be places where they are either used immediately or on commonly-used paths from that point forward.

**Comment by aplowman** [comment]
Yeah, thanks. I think by these commits: a42c0a9 and b6b579b.
