### ISSUE TITLE
RVE_extrusion_EBSD demo workflow doesn't work

### ISSUE THREAD

**Issue by gcapes** [hpcflow/matflow-new#266]
I have now tested this with MatFlow, version 0.3.0a132 in a new venv, with latest defdap, damask_parse and formable packages. The error comes in the first task 
<pre>┌────┬──────────────────────────────────────┬──────────┬────────────────────────────┬─────────────────────────────────────────────────────┐
│<b> ID </b>│<b> Name                                 </b>│<b> Status   </b>│<b> Times                      </b>│<b> Actions                                             </b>│
├────┼──────────────────────────────────────┼──────────┼────────────────────────────┼─────────────────────────────────────────────────────┤
│ 54 │ RVE_extrusion_EBSD_2024-11-25_102941 │ <font color="#767676">◊</font>/<font color="#0087FF">●</font>      │  <i>sb.</i>  2024-11-25 10:29:47  │  load_microstructure_EBSD            0 | <font color="#D70000">E</font>          │
│    │                                      │          │  <i>st.</i>             10:49:36  │  generate_volume_element_extrusion   0 | <font color="#FF8700">s</font>          │
│    │                                      │          │  <i>en.</i>             10:58:02  │  visualise_VE_VTK_1                  0 | <font color="#0087FF">●</font>          │
│    │                                      │          │                            │  modify_VE_add_buffer_zones          0 | <font color="#767676">.</font>          │
│    │                                      │          │                            │  visualise_VE_VTK_2                  0 | <font color="#767676">.</font>          │
│    │                                      │          │                            │  simulate_VE_loading_damask          0 | <font color="#767676">........</font>   │
│    │                                      │          │                            │                                                     │
</pre>

<pre>cat artifacts/submissions/0/js_0.sh.e5290224 
Traceback (most recent call last):
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 233, in &lt;module&gt;
    outputs = load_microstructure_EBSD(**direct_ins)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 24, in load_microstructure_EBSD
    EBSD_image = get_EBSD_image(ebsd_map, scaling_factor)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 67, in get_EBSD_image
    remove_small_grain_points(grain_image)
  File &quot;/net/scratch2/mbexegc2/patrick_curran/RVE_extrusion_EBSD_2024-11-25_102941/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py&quot;, line 194, in remove_small_grain_points
    for mode_val, mode_count in zip(mode_vals, mode_counts):
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: &apos;numpy.int64&apos; object is not iterable
</pre>

This demo workflow still runs in MatFlow version 0.3.0a110

**Comment by gcapes** [comment]
Running this workflow restricting the versions of packages to older versions as suggested here https://github.com/LightForm-group/non-repo-issues/issues/30#issuecomment-2498133900 gives this warning which is probably useful in terms of what needs to be fixed:

```
cat artifacts/submissions/0/js_0.sh.e5309806 
/net/scratch2/mbexegc2/patrick_curran/restricted_versions/execute/task_0_load_microstructure_EBSD/e_0/r_0/load_microstructure_EBSD.py:193: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_vals, mode_counts = mode(area)
```

**Comment by dkfellows** [comment]
Sounds like adding the `keepdims=True` keyword argument to the call to `scipy.stats.mode` will do the trick.  Worth a try...

**Comment by dkfellows** [comment]
Also review same code in `load_microstructure_EBSD_DIC.py`. Consider factoring out into true matflow member package so that the code to remove various points isn't repeated.

**Comment by gcapes** [comment]
I'm currently running a test job, with the modified `mode` call.

**Comment by gcapes** [comment]
The PR has been merged now so a new release is imminent.
https://github.com/hpcflow/matflow-new/pull/269
